### ISSUE TITLE
marian-decoder with fbgemm fails to run

### ISSUE THREAD

**Issue by jelmervdl** [paracrawl/cirrus-scripts#11]
Occurs at this commit: https://github.com/paracrawl/cirrus-scripts/tree/9b916b6a1b23f61f7d3d42f82ebc564ae85c102f

```
[cs-vand1@login-e-16 cirrus-scripts]$ gzip -cd /home/cs-vand1/r/internet_archive/wide00015-shards/zh/89/1/sentences.gz | b64filter cache foldfilter -s -w 5000 ./translate_zh_en.sh --cpu-threads 1 | gzip -9c > test.gz
[2020-11-09 18:05:14] [marian] Marian v1.9.37 40a9e3e 2020-10-26 11:09:39 +0000
[2020-11-09 18:05:14] [marian] Running on login-e-16 as process 31043 with command line:
[2020-11-09 18:05:14] [marian] marian-decoder-cpu -m /home/cs-vand1/src/cirrus-scripts/model.zhen.fbgemm.bin -v run02/vocab.zh.yml run02/vocab.en.yml -w 1024 --optimize --normalize 1 --word-penalty 0 --beam-size 4 --mini-batch-words 300 --maxi-batch 2000 --maxi-batch-sort src --shortlist /home/cs-vand1/src/cirrus-scripts/lex.zhen --cpu-threads 1
Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/tmp.xOgWPsoLsz/jieba.cache
Loading model cost 0.836 seconds.
Prefix dict has been built successfully.
[2020-11-09 18:05:38] [config] alignment: ""
[2020-11-09 18:05:38] [config] allow-unk: false
[2020-11-09 18:05:38] [config] authors: false
[2020-11-09 18:05:38] [config] beam-size: 4
[2020-11-09 18:05:38] [config] bert-class-symbol: "[CLS]"
[2020-11-09 18:05:38] [config] bert-mask-symbol: "[MASK]"
[2020-11-09 18:05:38] [config] bert-masking-fraction: 0.15
[2020-11-09 18:05:38] [config] bert-sep-symbol: "[SEP]"
[2020-11-09 18:05:38] [config] bert-train-type-embeddings: true
[2020-11-09 18:05:38] [config] bert-type-vocab-size: 2
[2020-11-09 18:05:38] [config] best-deep: false
[2020-11-09 18:05:38] [config] build-info: ""
[2020-11-09 18:05:38] [config] cite: false
[2020-11-09 18:05:38] [config] clip-gemm: 0
[2020-11-09 18:05:38] [config] cpu-threads: 1
[2020-11-09 18:05:38] [config] dec-cell: gru
[2020-11-09 18:05:38] [config] dec-cell-base-depth: 2
[2020-11-09 18:05:38] [config] dec-cell-high-depth: 1
[2020-11-09 18:05:38] [config] dec-depth: 1
[2020-11-09 18:05:38] [config] devices:
[2020-11-09 18:05:38] [config]   - 0
[2020-11-09 18:05:38] [config] dim-emb: 512
[2020-11-09 18:05:38] [config] dim-rnn: 1024
[2020-11-09 18:05:38] [config] dim-vocabs:
[2020-11-09 18:05:38] [config]   - 48770
[2020-11-09 18:05:38] [config]   - 35601
[2020-11-09 18:05:38] [config] dump-config: ""
[2020-11-09 18:05:38] [config] dump-quantmult: false
[2020-11-09 18:05:38] [config] enc-cell: gru
[2020-11-09 18:05:38] [config] enc-cell-depth: 1
[2020-11-09 18:05:38] [config] enc-depth: 1
[2020-11-09 18:05:38] [config] enc-type: bidirectional
[2020-11-09 18:05:38] [config] gemm-precision: int16
[2020-11-09 18:05:38] [config] ignore-model-config: false
[2020-11-09 18:05:38] [config] input:
[2020-11-09 18:05:38] [config]   - stdin
[2020-11-09 18:05:38] [config] input-types:
[2020-11-09 18:05:38] [config]   []
[2020-11-09 18:05:38] [config] int8tensorAlphaFused: false
[2020-11-09 18:05:38] [config] int8tensorFused: false
[2020-11-09 18:05:38] [config] interpolate-env-vars: false
[2020-11-09 18:05:38] [config] layer-normalization: true
[2020-11-09 18:05:38] [config] lemma-dim-emb: 0
[2020-11-09 18:05:38] [config] log: ""
[2020-11-09 18:05:38] [config] log-level: info
[2020-11-09 18:05:38] [config] log-time-zone: ""
[2020-11-09 18:05:38] [config] max-length: 1000
[2020-11-09 18:05:38] [config] max-length-crop: false
[2020-11-09 18:05:38] [config] max-length-factor: 3
[2020-11-09 18:05:38] [config] maxi-batch: 2000
[2020-11-09 18:05:38] [config] maxi-batch-sort: src
[2020-11-09 18:05:38] [config] mini-batch: 1
[2020-11-09 18:05:38] [config] mini-batch-words: 300
[2020-11-09 18:05:38] [config] models:
[2020-11-09 18:05:38] [config]   - /home/cs-vand1/src/cirrus-scripts/model.zhen.fbgemm.bin
[2020-11-09 18:05:38] [config] n-best: false
[2020-11-09 18:05:38] [config] no-spm-decode: false
[2020-11-09 18:05:38] [config] normalize: 1
[2020-11-09 18:05:38] [config] num-devices: 0
[2020-11-09 18:05:38] [config] output: stdout
[2020-11-09 18:05:38] [config] output-approx-knn:
[2020-11-09 18:05:38] [config]   []
[2020-11-09 18:05:38] [config] output-omit-bias: false
[2020-11-09 18:05:38] [config] output-sampling: false
[2020-11-09 18:05:38] [config] precision:
[2020-11-09 18:05:38] [config]   - float32
[2020-11-09 18:05:38] [config] quiet: false
[2020-11-09 18:05:38] [config] quiet-translation: false
[2020-11-09 18:05:38] [config] relative-paths: false
[2020-11-09 18:05:38] [config] right-left: false
[2020-11-09 18:05:38] [config] seed: 0
[2020-11-09 18:05:38] [config] shortlist:
[2020-11-09 18:05:38] [config]   - /home/cs-vand1/src/cirrus-scripts/lex.zhen
[2020-11-09 18:05:38] [config] skip: true
[2020-11-09 18:05:38] [config] skip-cost: false
[2020-11-09 18:05:38] [config] tied-embeddings: true
[2020-11-09 18:05:38] [config] tied-embeddings-all: false
[2020-11-09 18:05:38] [config] tied-embeddings-src: false
[2020-11-09 18:05:38] [config] transformer-aan-activation: swish
[2020-11-09 18:05:38] [config] transformer-aan-depth: 2
[2020-11-09 18:05:38] [config] transformer-aan-nogate: false
[2020-11-09 18:05:38] [config] transformer-decoder-autoreg: self-attention
[2020-11-09 18:05:38] [config] transformer-depth-scaling: false
[2020-11-09 18:05:38] [config] transformer-dim-aan: 2048
[2020-11-09 18:05:38] [config] transformer-dim-ffn: 2048
[2020-11-09 18:05:38] [config] transformer-ffn-activation: swish
[2020-11-09 18:05:38] [config] transformer-ffn-depth: 2
[2020-11-09 18:05:38] [config] transformer-guided-alignment-layer: last
[2020-11-09 18:05:38] [config] transformer-heads: 8
[2020-11-09 18:05:38] [config] transformer-no-projection: false
[2020-11-09 18:05:38] [config] transformer-pool: false
[2020-11-09 18:05:38] [config] transformer-postprocess: dan
[2020-11-09 18:05:38] [config] transformer-postprocess-emb: d
[2020-11-09 18:05:38] [config] transformer-postprocess-top: ""
[2020-11-09 18:05:38] [config] transformer-preprocess: ""
[2020-11-09 18:05:38] [config] transformer-tied-layers:
[2020-11-09 18:05:38] [config]   []
[2020-11-09 18:05:38] [config] transformer-train-position-embeddings: false
[2020-11-09 18:05:38] [config] tsv: false
[2020-11-09 18:05:38] [config] tsv-fields: 0
[2020-11-09 18:05:38] [config] type: s2s
[2020-11-09 18:05:38] [config] ulr: false
[2020-11-09 18:05:38] [config] ulr-dim-emb: 0
[2020-11-09 18:05:38] [config] ulr-trainable-transformation: false
[2020-11-09 18:05:38] [config] version: v1.7.8 63e1cfe 2019-02-11 21:04:00 -0800
[2020-11-09 18:05:38] [config] vocabs:
[2020-11-09 18:05:38] [config]   - run02/vocab.zh.yml
[2020-11-09 18:05:38] [config]   - run02/vocab.en.yml
[2020-11-09 18:05:38] [config] weights:
[2020-11-09 18:05:38] [config]   []
[2020-11-09 18:05:38] [config] word-penalty: 0
[2020-11-09 18:05:38] [config] word-scores: false
[2020-11-09 18:05:38] [config] workspace: 1024
[2020-11-09 18:05:38] [config] Loaded model has been created with Marian v1.7.8 63e1cfe 2019-02-11 21:04:00 -0800
[2020-11-09 18:05:38] [data] Loading vocabulary from JSON/Yaml file run02/vocab.zh.yml
[2020-11-09 18:05:38] [data] Loading vocabulary from JSON/Yaml file run02/vocab.en.yml
[2020-11-09 18:05:38] [data] Loading lexical shortlist as /home/cs-vand1/src/cirrus-scripts/lex.zhen 100 100 0
[2020-11-09 18:05:48] [memory] Extending reserved space to 1024 MB (device cpu0)
[2020-11-09 18:05:48] Loading scorer of type s2s as feature F0
[2020-11-09 18:05:48] Loading model from /home/cs-vand1/src/cirrus-scripts/model.zhen.fbgemm.bin
[2020-11-09 18:05:49] [memory] Reserving 237 MB, device cpu0
[2020-11-09 18:05:49] [memory] Reserving 14 MB, device cpu0
[2020-11-09 18:05:49] Error: Rows of matrix: param must be multiple of 8.
[2020-11-09 18:05:49] Error: Aborted from marian::cpu::integer::PrepareBNodeOp<vtype>::PrepareBNodeOp(marian::Expr, marian::Expr, float, bool) [with marian::Type vtype = (marian::Type)258; marian::Expr = IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase> > >] in /home/cs-vand1/src/cirrus-scripts/env/src/marian-fbgemm/src/tensors/cpu/intgemm_interface.h:77

[CALL STACK]
[0x9d36ae]          marian::cpu::integer::PrepareBNodeOp<(marian::Type)258>::  PrepareBNodeOp  (IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>,  IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>,  float,  bool) + 0x64e
[0x9d448d]          IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>> marian::  Expression  <marian::cpu::integer::PrepareBNodeOp<(marian::Type)258>,IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>&,IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>&,float&,bool&>(IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>&,  IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>&,  float&,  bool&) + 0x6d
[0xa3a869]          marian::mlp::Output::  applyAsLogits  (IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>) + 0x3849
[0xae4b06]          marian::mlp::MLP::  applyAsLogits  (std::vector<IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>,std::allocator<IntrusivePtr<marian::Chainable<IntrusivePtr<marian::TensorBase>>>>> const&) + 0x1c6
[0xb0b84a]          marian::DecoderS2S::  step  (std::shared_ptr<marian::ExpressionGraph>,  std::shared_ptr<marian::DecoderState>) + 0x67a
[0xb32c64]          marian::EncoderDecoder::  step  (std::shared_ptr<marian::ExpressionGraph>,  std::shared_ptr<marian::DecoderState>,  std::vector<unsigned int,std::allocator<unsigned int>> const&,  std::vector<marian::Word,std::allocator<marian::Word>> const&,  std::vector<unsigned int,std::allocator<unsigned int>> const&,  int) + 0x194
[0xa85a23]          marian::models::Stepwise::  step  (std::shared_ptr<marian::ExpressionGraph>,  std::shared_ptr<marian::DecoderState>,  std::vector<unsigned int,std::allocator<unsigned int>> const&,  std::vector<marian::Word,std::allocator<marian::Word>> const&,  std::vector<unsigned int,std::allocator<unsigned int>> const&,  int) + 0x83
[0x816aed]          marian::BeamSearch::  search  (std::shared_ptr<marian::ExpressionGraph>,  std::shared_ptr<marian::data::CorpusBatch>) + 0x2e2d
[0x6a11f0]          marian::Translate<marian::BeamSearch>::run()::{lambda(unsigned long)#1}::  operator()  (unsigned long) const + 0x140
[0x6a19f8]          marian::ThreadPool::enqueue<marian::Translate<marian::BeamSearch>::run()::{lambda(unsigned long)#1}&,unsigned long>(std::result_of&&,(marian::Translate<marian::BeamSearch>::run()::{lambda(unsigned long)#1}&)...)::{lambda()#1}::  operator()  () const + 0x18
[0x6a2500]          std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base,std::__future_base::_Result_base::_Deleter> (),std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>,std::__future_base::_Result_base::_Deleter>,std::__future_base::_Task_state<marian::ThreadPool::enqueue<marian::Translate<marian::BeamSearch>::run()::{lambda(unsigned long)#1}&,unsigned long>(std::result_of&&,(marian::Translate<marian::BeamSearch>::run()::{lambda(unsigned long)#1}&)...)::{lambda()#1},std::allocator<int>,void ()>::_M_run()::{lambda()#1},void>>::  _M_invoke  (std::_Any_data const&) + 0x20
[0x650e7b]          std::__future_base::_State_baseV2::  _M_do_set  (std::function<std::unique_ptr<std::__future_base::_Result_base,std::__future_base::_Result_base::_Deleter> ()>*,  bool*) + 0x1b
[0x2b72b140920b]                                                       + 0x620b
[0x6529e3]          std::__future_base::_Task_state<marian::ThreadPool::enqueue<marian::Translate<marian::BeamSearch>::run()::{lambda(unsigned long)#1}&,unsigned long>(std::result_of&&,(marian::Translate<marian::BeamSearch>::run()::{lambda(unsigned long)#1}&)...)::{lambda()#1},std::allocator<int>,void ()>::  _M_run  () + 0xe3
[0x652de0]          std::thread::_State_impl<std::thread::_Invoker<std::tuple<marian::ThreadPool::reserve(unsigned long)::{lambda()#1}>>>::  _M_run  () + 0x130
[0x2b72b1cc830f]                                                       + 0xbb30f
[0x2b72b140aea5]                                                       + 0x7ea5
[0x2b72b25a98dd]    clone                                              + 0x6d

Traceback (most recent call last):
  File "/home/cs-vand1/src/cirrus-scripts/env/bin/subword-nmt", line 10, in <module>
    sys.exit(main())
  File "/home/cs-vand1/src/cirrus-scripts/env/lib/python3.8/site-packages/subword_nmt/subword_nmt.py", line 73, in main
    args.output.write(bpe.process_line(line, args.dropout))
  File "/usr/local/software/master/python/3.8/lib/python3.8/codecs.py", line 378, in write
    self.stream.write(data)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <encodings.utf_8.StreamWriter object at 0x2b9fa8aa9310>
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/software/master/python/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/software/master/python/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/cs-vand1/src/cirrus-scripts/env/lib/python3.8/site-packages/jieba/__main__.py", line 58, in <module>
    print(result)
BrokenPipeError: [Errno 32] Broken pipe
./translate_zh_en.sh: line 30: 31041 Exit 1                  TMPDIR=$JIEBA_TMP python -m jieba -d ' '
     31042 Exit 120                | subword-nmt apply-bpe -c prepare01/bpe.model.zh
     31043 Aborted                 | marian-decoder-cpu -m /home/cs-vand1/src/cirrus-scripts/model.zhen.fbgemm.bin -v run02/vocab.{zh,en}.yml -w 1024 --optimize --normalize 1 --word-penalty 0 --beam-size 4 --mini-batch-words 300 --maxi-batch 2000 --maxi-batch-sort src --shortlist /home/cs-vand1/src/cirrus-scripts/lex.zhen "$@"
     31044 Done                    | perl -pe 's/@@ //g'
     31045 Done                    | $MOSES/scripts/recaser/detruecase.perl
     31046 Done                    | $MOSES/scripts/tokenizer/detokenizer.perl -q -l en
```

**Comment by jelmervdl** [comment]
I don't think this issue is up-to-date or relevant anymore. I'll re-open it if I encounter it again.
